### ISSUE TITLE
Specs to be fixed for ubuntu-22.04

### ISSUE THREAD

**Issue by oleksii-leonov** [telus-agcg/ffi-gdal#85]
There are 4 specs failing on `ubuntu-22.04` (GDAL 3.4.1):

- [x] spec/integration/gdal/raster_band_info_spec.rb:181 # Raster Band Info #scale returns a Float (PR #84)
```
  1) Raster Band Info #scale returns a Float
     Failure/Error: raise GDAL::Error, "GDALGetRasterScale failed" unless success.read_bytes(1).to_bool

     GDAL::Error:
       GDALGetRasterScale failed
     # ./lib/gdal/raster_band.rb:355:in `scale'
     # ./spec/integration/gdal/raster_band_info_spec.rb:182:in `block (3 levels) in <top (required)>'
```

- [x] spec/integration/gdal/raster_band_info_spec.rb:194 # Raster Band Info #offset returns a Float (PR #84)
```
2) Raster Band Info #offset returns a Float
     Failure/Error: raise GDAL::Error, "GDALGetRasterOffset failed" unless success.read_bytes(1).to_bool

     GDAL::Error:
       GDALGetRasterOffset failed
     # ./lib/gdal/raster_band.rb:384:in `offset'
     # ./spec/integration/gdal/raster_band_info_spec.rb:195:in `block (3 levels) in <top (required)>'
```

- [x] spec/integration/gdal/dataset_info_spec.rb:163 # Dataset Info #geo_transform= read-only dataset raises a GDAL::UnsupportedOperation (PR #86)
```
  3) Dataset Info #geo_transform= read-only dataset raises a GDAL::UnsupportedOperation
     Failure/Error: expect { subject.geo_transform = geo_transform }.to raise_exception GDAL::UnsupportedOperation
       expected GDAL::UnsupportedOperation but nothing was raised
     # ./spec/integration/gdal/dataset_info_spec.rb:164:in `block (4 levels) in <top (required)>'
```

- [x] spec/unit/ogr/extensions/geometry/rttopo_extensions_spec.rb:38 # OGR::Geometry#make_valid crossing lines makes a valid MULTIPOLYGON _(slightly different polygon returned, due to newer rttopo version)_ (PR #88)
```
4) OGR::Geometry#make_valid crossing lines makes a valid MULTIPOLYGON
     Failure/Error: expect(subject.make_valid.to_wkt).to eq(ci_expected_wkt).or eq(local_expected_wkt)

          expected: #<Encoding:UTF-8> "MULTIPOLYGON (((0 0,0 10,3.33333333333333 6.66666666666667,0 0)),((3.33333333333333 6.66666666666667,5 10,5 5,3.33333333333333 6.66666666666667)),((10 0,5 0,5 5,10 0)))"
               got: #<Encoding:ASCII-8BIT> "MULTIPOLYGON (((10 0,5 0,5 5,10 0)),((3.33333333333333 6.66666666666667,0 0,0 10,3.33333333333333 6.66666666666667)),((5 10,5 5,3.33333333333333 6.66666666666667,5 10)))"
```

**Comment by oleksii-leonov** [comment]
`ubuntu-22.04` support is ready in PR #97.
